### ISSUE TITLE
Icons not displayed

### ISSUE THREAD

**Issue by steveriley1964** [vlaine/Weather-Forecast-Dashboard#1]
Hi,

This is a lovely looking front-end, but my system refuses to show the weather icons.  Do you have any thoughts for what may be happening or where to look to fix it?
I have tried it on both Wheezy and Stretch - I guess that I am missing some software.

Cheers,
Steve.

**Comment by vlaine** [comment]
Icons are included in the icons folder.  
1. Make sure that you downloaded the entire code and didn't change the folder structure.  
2. In the config.js file, make sure you put your api key
var apiKey = "PUT_YOUR_API_KEY_HERE"; // darksky.net api key
3. In the script.js file, you can uncomment the sample data section and comment the entire $ajax call to check if the problem is with the call to the darksky api.  

If you still have issue, you can post your config.js file here (remove your personal api key)

**Comment by steveriley1964** [comment]
Hi vlaine.  Thank you for replying.

Still no joy I'm afraid.  The data from darksky appears without a problem.  I have tried changing the colours of the icon backgrounds in script.js, which verified where the icons were supposed to appear.  The sample data appears with the alert banner - pretty chilly :-)

I have copied the contents of Weather-Forecast-Dashboard into /var/www/html and ensured that the userid and group were consistent with the Apache2 daemon - root:www-data.

I also tried using git-clone and the zip file.

Here's my config.js:
var apiKey = "API Key HERE"; // darksky.net api key
var latitude = "53.429146"; // My office
var longitude = "-2.534477"; // My office
var lang = "en"; // too many options.  check here https://darksky.net/dev/docs/forecast
var units = "uk2"; // auto, ca, uk2, us, si
var degreeSymbol = "C"; // C or F
var rainPrecUnit = "mm";
var snowPrecUnit = "cm";
var windUnit = "km/h"
var forecastNbOfDays = 8; // 0 to 8
var hourlyNbOfHours = 12; // 0-49

var showScrollingAlerts = true;
var showCurrentWeather = true;
var showCurrentIcon = true;
var showCurrentSummary = true;
var showCurrentDate = true;
var showCurrentTime = true;
var showForecastIcon = true;
var showForecastSummary = true;
var showForecastMinTemp = true;
var showForecastAccumulation = true;
var showForecastProbability = true;
var showHourlyIcon = true;
var showHourlyAccumulation = true;
var showHourlyProbability = true;
var showDarkSkyLink = true; // set to true if you have a free darksky api key.

var debugging = false; // will allow showing forecast for past days.  Usefull when playing with sample data

// Set for your language
// English
var todayLabel = "Today";
var windLabel = "wind";
var apparentTempLabel = "feeling";
var week = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
var month = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];

// French
//var todayLabel = "Aujourd'hui";
//var windLabel = "vent";
//var apparentTempLabel = "ressentie";
//var week = ['Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi'];
//var month = ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'];

var url = 'https://api.darksky.net/forecast/' + apiKey + '/' + latitude + ',' + longitude + '?lang=' + lang + '&units=' + units;

**Comment by steveriley1964** [comment]
Apologies!  Fixed.  I kept all the files in /var/www/html/Weather-Forecast-Dashboard and pointed to the index.html in there.  It has burst into life.  Lovely.

Many thanks for your time.

Steve.
