### ISSUE TITLE
Display

### ISSUE THREAD

**Issue by safadig** [vlaine/Weather-Forecast-Dashboard#2]
I must admit that this is my first knowledge of Raspberry PI.  The dashboard looks amazing. Curious as to what is the Display you used? Definitely giving this a try. Thanks

**Comment by vlaine** [comment]
I use a Waveshare 7’’ display that I purchased from Aliexpress. For my family I purchased 52Pi 7’’ displays, again from AliExpress.  It doesn’t have to cost a lot and a touch screen is not required.
