### ISSUE TITLE
Adding Humidity

### ISSUE THREAD

**Issue by adam-wood** [vlaine/Weather-Forecast-Dashboard#3]
Hi vlaine,

Great little project. I tried taking a look at the script.js to see if I could modify it to show humidity data but got a bit stuck. Would be great if you could add that as an option to current, hourly & forecast.

If not, it would be great if you could give me a few pointers on the sections where I would need to duplicate & modify some lines to make this work would be appreciated. My code skills are pretty basic and I can't seem to figure out which lines deal with parsing out the various data values.

**Comment by vlaine** [comment]
Humidity is now included.  The doc will be updated later if I find the motivation.
